// Generated by scripts/export-admin-art.mjs. 原画の版を変えたら再生成する。
export const ADMIN_ART = {
  'black-hole': {
    src: '/assets/admin-celestial-black-hole.webp?v=27123211',
    width: 192,
    height: 108,
    source: '/assets/blackhole.webp?v=c48dd421',
  },
  sun: {
    src: '/assets/admin-celestial-sun.webp?v=b00c8298',
    width: 192,
    height: 192,
    source: '/assets/celestial-sun-v2.webp?v=0383b12e',
  },
  moon: {
    src: '/assets/admin-celestial-moon.webp?v=bb31e9c9',
    width: 192,
    height: 192,
    source: '/assets/celestial-moon-v2.webp?v=99af9d0a',
  },
  neptune: {
    src: '/assets/admin-celestial-neptune.webp?v=ef9f12d4',
    width: 192,
    height: 192,
    source: '/assets/celestial-neptune-v2.webp?v=568d3093',
  },
  saturn: {
    src: '/assets/admin-celestial-saturn.webp?v=22f9afa4',
    width: 192,
    height: 192,
    source: '/assets/celestial-saturn-v2.webp?v=7eb69c84',
  },
} as const
