// Generated by scripts/ascii/render.mjs. Regenerate assets and URL versions together.
export const ASCII_ART = {
  'black-hole': {
    motion: '/assets/ascii-black-hole.svg?v=ef87973c',
    still: '/assets/ascii-black-hole-still.svg?v=07fb45c0',
  },
  saturn: {
    motion: '/assets/ascii-saturn.svg?v=8e4a5d9d',
    still: '/assets/ascii-saturn-still.svg?v=13357018',
  },
  neptune: {
    motion: '/assets/ascii-neptune.svg?v=f8cd09d5',
    still: '/assets/ascii-neptune-still.svg?v=15030c32',
  },
  moon: {
    motion: '/assets/ascii-moon.svg?v=82bfb9b7',
    still: '/assets/ascii-moon-still.svg?v=e197b859',
  },
  sun: {
    motion: '/assets/ascii-sun.svg?v=9e88961f',
    still: '/assets/ascii-sun-still.svg?v=9eead00f',
  },
  nebula: {
    motion: '/assets/ascii-nebula.svg?v=7e118d96',
    still: '/assets/ascii-nebula-still.svg?v=d6c34dbe',
  },
} as const
